---
title: "All Correlations"
author: "Alicia Key"
date: "2022-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the libraries

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(broom)
library(stringr)
library(here)
```

## Read the data

```{r}
reds_iii_iv <- read_excel(here("input", "Recall vs Index correlations.xlsx"), sheet = "REDSIII_IV-subj-met_matched")

reds_iv_recall <- read_excel(here("input", "Recall vs Index correlations.xlsx"), sheet = "REDSIV_Recall42_met-matched")
```

## Pivot and join the data

```{r}
reds_iii_iv_long <- reds_iii_iv %>%
  pivot_longer(-rti_id, values_to = "IndexNormalizedAbundance", names_to = "Metabolite") %>%
  distinct(rti_id, Metabolite, IndexNormalizedAbundance)

reds_iv_recall_long <- reds_iv_recall %>%
  pivot_longer(-rti_id, values_to = "RecallNormalizedAbundance", names_to = "Metabolite") %>%
  distinct(rti_id, Metabolite, RecallNormalizedAbundance)

recall_and_index <- reds_iii_iv_long %>%
  inner_join(reds_iv_recall_long, by = c("rti_id", "Metabolite"), relationship = "one-to-one") %>%
  arrange(rti_id, Metabolite)

write.csv(recall_and_index, "output/recall_and_index.csv", row.names = FALSE)
```

## Remove outliers

```{r}
lower_bound_sd <- 3
upper_bound_sd <- 3

filtered_reacall_and_index <- recall_and_index %>%
  group_by(Metabolite) %>%
  mutate(
    IndexLowerBound = mean(IndexNormalizedAbundance) - lower_bound_sd * sd(IndexNormalizedAbundance),
    RecallLowerBound = mean(RecallNormalizedAbundance) - lower_bound_sd * sd(RecallNormalizedAbundance),
    IndexUpperBound = mean(IndexNormalizedAbundance)  + upper_bound_sd * sd(IndexNormalizedAbundance),
    RecallUpperBound = mean(RecallNormalizedAbundance) + upper_bound_sd * sd(RecallNormalizedAbundance)
  ) %>%
  ungroup() %>%
  filter(
    IndexNormalizedAbundance > IndexLowerBound,
    IndexNormalizedAbundance < IndexUpperBound,
    RecallNormalizedAbundance > RecallLowerBound,
    RecallNormalizedAbundance < RecallUpperBound
  )
```

## Find the correlations

```{r}
recall_and_index_correlations <- filtered_reacall_and_index %>%
  group_by(Metabolite) %>%
  summarize(
    rho = cor.test(
      IndexNormalizedAbundance, 
      RecallNormalizedAbundance,
      method = "spearman",
      exact = FALSE
    )$estimate,
    
    p = cor.test(
      IndexNormalizedAbundance, 
      RecallNormalizedAbundance,
      method = "spearman",
      exact = FALSE
    )$p.value
  )

write.csv(recall_and_index_correlations, here("output", "recall_and_index_correlations.csv"), row.names = FALSE)

recall_and_index_correlations
```

## Plot the signifcant correlations

And fit their linear models.

```{r}
p_cutoff <- 0.05
rho_cutoff <- 0.25

metabolite_list <- recall_and_index_correlations %>%
  filter(p < p_cutoff, rho > rho_cutoff) %>%
  pull(Metabolite)

for (m in metabolite_list) {
  recall_and_index_for_metabolite <- recall_and_index %>%
    filter(Metabolite == m)
  
  metabolite_lm_tidy <- glance(lm(RecallNormalizedAbundance ~ IndexNormalizedAbundance, data = recall_and_index_for_metabolite))
  
  r_squared <- metabolite_lm_tidy$r.squared
  
  rho <- recall_and_index_correlations %>%
    filter(Metabolite == m) %>%
    pull(rho)
  
  p_value <- recall_and_index_correlations %>%
    filter(Metabolite == m) %>%
    pull(p)
  
  metabolite_plot <- recall_and_index_for_metabolite %>%
    ggplot(aes(y = RecallNormalizedAbundance, x = IndexNormalizedAbundance)) +
    geom_point(alpha = 0.5) +
    geom_smooth(method = "lm", color = "red", se = FALSE) +
    labs(title = m, subtitle = paste("rho=", format(rho, digits = 4), ", p=", format(p_value, digits = 3), sep = "")) +
    xlab("Index Donation (REDS III)") +
    ylab("Recall Donation (REDS IV)") +
    theme_minimal() +
    theme(plot.background = element_rect(fill = "white")) +
    theme(
      plot.title = element_text(size = 18, face = "bold"),
      plot.subtitle = element_text(size = 18),
      axis.title = element_text(size = 10, face = "bold"),
      axis.text = element_text(size = 10)
    )
  
  output_filename <- paste(m %>%
                              str_replace_all("\'", "_") %>%
                              str_replace_all("\\/", "_") %>%
                              str_replace_all(":", "_"),
                            ".png",
                            sep = "")
  
  ggsave(here("output", "plots", output_filename), plot = metabolite_plot, dpi = 300, units = "in", width = 5, height = 5)
  
  print(paste("Saved", output_filename))
}
```
